#!/bin/bash
creatorOption=$(zenity --list --title="Patreon Downloader" --column="Creator" --column="Creator URL" Snailords "https://www.patreon.com/Snailords/posts" \
Refrainbow "https://www.patreon.com/refrainbow/posts" \
Telepurte "https://www.patreon.com/m/2235165/posts" \
Other "Input URL Manually")
if [[ $creatorOption = "Snailords" ]]
then
  echo "Snailords Command"
  zenity --info --title="Downoad Started" --text="Patreon downloader has started to save content from $creatorOption, you will be notified when it's complete." --no-wrap
  ./PatreonDownloader.App --descriptions --embeds --json --campaign-images --url https://www.patreon.com/Snailords/posts
  notify-send "Patreon Downloader" "Download complete: $creatorOption"
elif [[ $creatorOption = "Refrainbow" ]]
then
  echo "Refrainbow Command"
  zenity --info --title="Downoad Started" --text="Patreon downloader has started to save content from $creatorOption, you will be notified when it's complete." --no-wrap
  ./PatreonDownloader.App --descriptions --embeds --json --campaign-images --url https://www.patreon.com/Snailords/posts
  notify-send "Patreon Downloader" "Download complete: $creatorOption"
elif [[ $creatorOption = "Telepurte" ]]
then
  echo "Telepurte Command"
  zenity --info --title="Downoad Started" --text="Patreon downloader has started to save content from $creatorOption, you will be notified when it's complete." --no-wrap
  ./PatreonDownloader.App --descriptions --embeds --json --campaign-images --url https://www.patreon.com/m/2235165/posts
  notify-send "Patreon Downloader" "Download complete: $creatorOption"
elif [[ $creatorOption = "Other" ]]
then
    # Manual Option
    
    customUrl=$(zenity --entry --text="Enter the URL ending in ''/posts'':" --title="Enter Creator URL")
    if [ -n "$customUrl" ]
    then
        zenity --info --title="Downoad Started" --text="Patreon downloader has started to save content from the specified creator, you will be notified when it's complete." --no-wrap
        downloadIsSuccessCheck=$(./PatreonDownloader.App --descriptions --embeds --json --campaign-images --url $customUrl)
        downloadIsFailUrl=$(echo $downloadIsSuccessCheck | grep -i -o 'Download url should start with')
        downloadIsFinish=$(echo $downloadIsSuccessCheck | grep -i -o 'INFO Finished')       
        echo "downloadIsFailUrl is $downloadIsFailUrl ..." #debug
        echo "downloadIsFinish is $downloadIsFinish ..." #debug
        # Checking for download fail - reason of invalid patreon URL
            if [[ -z "$downloadIsFailUrl" ]] #If var is empty, true
                then
                    echo "empty fail var - proceeding..."
                elif [[ $downloadIsFailUrl = "Download url should start with" ]]
                    then
                        echo "Fail Error Case - Invalid URL"
                        zenity --error --title="Error" --text="Unable to proceed - Invalid Patreon URL" --no-wrap
                elif [[ $downloadIsFinish = "INFO Finished" ]]
                    then
                        notify-send "Patreon Downloader" "Custom download complete"
                else
                    echo "script error - debug in command line"
                    echo "The variable downloadIsFailUrl is $downloadIsFailUrl ..."
                    echo "The variable downloadIsSuccessCheck is $downloadIsSuccessCheck ..."
                    zenity --error --title="Error" --text="Unexpected Error! - Please re-run the script in terminal and file a github issue with the output." --no-wrap
        fi
    fi  
  #end manual option
else
  echo "Other Command No Input"
  zenity --info --title="Notice" --text="The script completed without downloading anything." --no-wrap
fi
echo "Done"
